/**
 * Publishes the built phone app to the small PUBLIC repo that GitHub Pages
 * serves it from:
 *
 *   npm run publish:phone
 *
 * Why a separate repo: NihilPointZeroStudio is private, and GitHub Pages cannot
 * serve a private repo on a free plan. Rather than make the studio source public,
 * only the phone app's built output — index.html, one JS bundle, a manifest, a
 * service worker and icons — lives in the public repo. No source, no keys, no
 * user work ever goes there.
 *
 * This touches nothing on the PC and nothing in the desktop app. It only copies
 * `phone/dist` into a temporary clone and pushes it.
 */
import { execFileSync } from 'node:child_process'
import { cpSync, existsSync, mkdtempSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const DIST = join(ROOT, 'phone', 'dist')
const REPO = process.env.NPZ_PHONE_REPO || 'https://github.com/DSKJazz/nihilpointzero-phone.git'
const BRANCH = 'main'

if (!existsSync(DIST) || !readdirSync(DIST).length) {
  console.error('phone/dist is empty — run `npm run build:phone` first.')
  process.exit(1)
}

/**
 * The public repo's front page. It exists to make clear to anyone who stumbles
 * on the repo what this is — and, just as importantly, what it is NOT: it holds
 * no studio source, no keys and no user data.
 */
const PUBLIC_README = `# NihilPointZero — phone app

The phone companion for NIHILPOINTZERO-OS, a finance/economics video studio.

**Open it here:** https://dskjazz.github.io/nihilpointzero-phone/

On a phone, open that link and choose **Install app** (or *Add to Home screen*)
from the browser menu to get it as a home-screen app. It works offline-tolerant
and needs no account.

It writes video ideas, full scripts and thumbnail briefs, and has a strategy
advisor. Video rendering, voice-over and subtitles are not here — those run in
the desktop studio.

By default it uses a free, keyless AI endpoint. You can optionally supply your
own Claude or OpenAI key in Settings; that key is stored only in your own
browser and is sent only to that provider.

---

This repository contains **only the built static site** — HTML, one JS bundle, a
manifest, a service worker and icons. It contains no studio source code, no API
keys, and no user data. It is generated by \`npm run publish:phone\` in the
private studio repository; edit it there, not here.
`

const work = mkdtempSync(join(tmpdir(), 'npz-phone-'))
const git = (...args) => execFileSync('git', args, { cwd: work, stdio: 'inherit' })

try {
  console.log(`Cloning ${REPO} …`)
  execFileSync('git', ['clone', '--depth', '1', REPO, work], { stdio: 'inherit' })

  // Wipe the tracked files but keep .git, so files deleted from the build also
  // disappear from the published site instead of lingering forever.
  for (const entry of readdirSync(work)) {
    if (entry === '.git') continue
    rmSync(join(work, entry), { recursive: true, force: true })
  }

  cpSync(DIST, work, { recursive: true })

  // Stops GitHub Pages running the output through Jekyll, which would otherwise
  // ignore any file or folder beginning with an underscore.
  writeFileSync(join(work, '.nojekyll'), '')
  writeFileSync(join(work, 'README.md'), PUBLIC_README)

  git('add', '-A')
  const changed = execFileSync('git', ['status', '--porcelain'], { cwd: work, encoding: 'utf8' }).trim()
  if (!changed) {
    console.log('Phone app is already up to date — nothing to publish.')
  } else {
    git('commit', '-m', 'Update NihilPointZero phone app')
    git('push', 'origin', BRANCH)
    console.log('\nPublished. The phone app updates within a minute or two at:')
    console.log('  https://dskjazz.github.io/nihilpointzero-phone/')
  }
} finally {
  rmSync(work, { recursive: true, force: true })
}
